services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    depends_on:
      - mysqldb
    container_name: pipeline-tp-foyer
    image: samarboughanmi/tp-foyer:5.0.0
    ports:
      - 8089:8089
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: >
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "root",
          "spring.jpa.hibernate.ddl-auto": "update",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
          "management.endpoints.web.exposure.include": "*",
          "management.endpoint.prometheus.enabled": true
        }
    stdin_open: true
    tty: true

volumes:
  db:

