version: '3.8'

services:
  mysql-test:
    image: mysql:5.7
    container_name: mysql-test
    ports:
      - "3307:3306"  # port 3307 sur l'hôte
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    restart: always